### ISSUE TITLE
Doesn't work without spatial_dataset_identifier_code

### ISSUE THREAD

**Issue by joto** [qgisinspiretools/qgis-inspire-atom-client-plugin#11]
The plugin doesn't work if there is no `inspire_dls:spatial_dataset_identifier_code`. Maybe without that the atom link isn't fully conformant, but would be nice if it works anyway.

Example: https://geodownload.sachsen.de/inspire/el_atom/Dataset_el_dgm1.xml

**Comment by ejn** [comment]
I believe that the problem here is that you are trying to directly open the dataset feed, rather than first opening the service feed (https://geodownload.sachsen.de/inspire/el_atom/Service_el.xml), from which you can then select and download the dataset.

It would no doubt be possible to directly open the dataset feed, but I would put this one more down to false expectations (and possibly insufficiently clear UI - it should maybe say INSPIRE ATOM Service-Feed URL above the URL input field).

**Comment by joto** [comment]
Yeah, sorry, that might well be. There is basically no documentation either for the plugin or how those atom feeds are supposed to be used, so I am stumbling around in the dark here.
